name: Deploy to AWS ECS

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  Setup_Java:
    runs-on: ubuntu-latest
    outputs:
      RUNNER: ${{ runner.name }}
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 21 for x64
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'corretto'
          architecture: x64
          cache: maven

  Build_Maven_App:
    runs-on: ${{needs.Setup_Java.outputs.RUNNER}}
    needs: Setup_Java
    steps:
      - uses: actions/checkout@v2
      - name: Java version
        run: java --version
      - name: Run the Maven verify phase
        run: mvn --batch-mode --update-snapshots verify
      - name: List target
        run: cd target/ && ls -l
